default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: slack_test_development

test:
  <<: *default
  database: slack_test_test

production:
  <<: *default
  database: slack_test_production
